// <auto-generated />
namespace CourseManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create));
        
        string IMigrationMetadata.Id
        {
            get { return "201912040050167_create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
